/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package temperatura;

import javax.swing.JOptionPane;

/**
 *
 * @author info7
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonera = new javax.swing.ButtonGroup();
        itemSelector = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        checkCelsius = new javax.swing.JRadioButton();
        checkKelvin = new javax.swing.JRadioButton();
        checkFahrenheit = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btnConvertir = new javax.swing.JButton();
        txtTemperatura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resultadoTemp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itemSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Kelvin", "Fahrenheit" }));
        itemSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSelectorActionPerformed(evt);
            }
        });

        jLabel1.setText("De grados...");

        botonera.add(checkCelsius);
        checkCelsius.setText("Celsius");
        checkCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCelsiusActionPerformed(evt);
            }
        });

        botonera.add(checkKelvin);
        checkKelvin.setText("Kelvin");
        checkKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkKelvinActionPerformed(evt);
            }
        });

        botonera.add(checkFahrenheit);
        checkFahrenheit.setText("Fahrenheit");
        checkFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFahrenheitActionPerformed(evt);
            }
        });

        jLabel2.setText("A...");

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        txtTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaActionPerformed(evt);
            }
        });

        jLabel3.setText("Temperatura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkKelvin)
                                    .addComponent(checkCelsius)
                                    .addComponent(itemSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(checkFahrenheit)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(btnConvertir)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(resultadoTemp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkCelsius)
                .addGap(4, 4, 4)
                .addComponent(checkKelvin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkFahrenheit)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(btnConvertir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultadoTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemSelectorActionPerformed

    private void checkCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCelsiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkCelsiusActionPerformed

    private void checkKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkKelvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkKelvinActionPerformed

    private void checkFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkFahrenheitActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
        
        String resultado = null;
        
        double temp = 0;
        String letra = "";

        
        Conversor convertir = new Conversor();
        
        if(txtTemperatura.getText().length() != 0){
            temp = Double.parseDouble(txtTemperatura.getText());
            
            if(itemSelector.getSelectedItem().toString().equals("Celsius") && checkFahrenheit.isSelected()){
                resultado = String.valueOf(convertir.celsiusToFahrenheit(temp));
                letra = "F";
            }
            if(itemSelector.getSelectedItem().toString().equals("Celsius") && checkKelvin.isSelected()){
                resultado = String.valueOf(convertir.celsiusToKelvin(temp));
                letra = "K";
            }
            if(itemSelector.getSelectedItem().toString().equals("Fahrenheit") && checkCelsius.isSelected()){
                resultado = String.valueOf(convertir.FahrenheitToCelsius(temp));
                letra = "C";
            }
            if(itemSelector.getSelectedItem().toString().equals("Fahrenheit") && checkKelvin.isSelected()){
                resultado = String.valueOf(convertir.FahrenheitToKelvin(temp));
                letra = "K";
            }
             if(itemSelector.getSelectedItem().toString().equals("Kelvin") && checkCelsius.isSelected()){
                resultado = String.valueOf(convertir.KelvinToCelsius(temp));
                letra = "C";
            }
            if(itemSelector.getSelectedItem().toString().equals("Kelvin") && checkFahrenheit.isSelected()){
                resultado = String.valueOf(convertir.KelvinToFahrenheit(temp));
                letra = "F";
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe ingresar un valor de temperatura");
        }
        resultadoTemp.setText("Resultado: " + resultado + "°" + letra);
        
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void txtTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botonera;
    private javax.swing.JButton btnConvertir;
    private javax.swing.JRadioButton checkCelsius;
    private javax.swing.JRadioButton checkFahrenheit;
    private javax.swing.JRadioButton checkKelvin;
    private javax.swing.JComboBox<String> itemSelector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel resultadoTemp;
    private javax.swing.JTextField txtTemperatura;
    // End of variables declaration//GEN-END:variables
}
